## Practice Notebook

In [2]:
# !pip install pydantic==1.10.11

In [3]:
from langchain.document_loaders import TextLoader

In [4]:
dir

<function dir>

In [5]:
ls

 Volume in drive D is Personal
 Volume Serial Number is 76D7-73A5

 Directory of D:\LangChain\langchain-main\2_news_research_tool_project\notebooks

10/31/2023  09:05 AM    <DIR>          .
10/29/2023  11:31 PM    <DIR>          ..
10/31/2023  09:03 AM    <DIR>          .ipynb_checkpoints
10/29/2023  11:31 PM            22,588 chunk_size.jpg
10/31/2023  09:03 AM            13,114 faiss_tutorial.ipynb
10/29/2023  11:31 PM               881 movies.csv
10/29/2023  11:31 PM             4,628 nvda_news_1.txt
10/31/2023  09:03 AM            45,259 retrieval.ipynb
10/29/2023  11:31 PM               516 sample_text.csv
10/31/2023  09:03 AM            36,294 text_loaders_splitters.ipynb
10/31/2023  09:05 AM             1,079 Untitled.ipynb
10/29/2023  11:31 PM           291,235 vector_index.pkl
               9 File(s)        415,594 bytes
               3 Dir(s)  93,046,284,288 bytes free


In [7]:
# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [8]:
df = pd.read_csv('sample_text.csv')
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [9]:
from sentence_transformers import SentenceTransformer

In [12]:
encoder = SentenceTransformer('all-mpnet-base-v2')
vectors = encoder.encode(df.text)

In [13]:
vectors

array([[-0.00247394,  0.03626722, -0.05290459, ..., -0.09152357,
        -0.03969999, -0.04330488],
       [-0.03357266,  0.00980516, -0.03250129, ..., -0.05165465,
         0.02245889, -0.03156183],
       [-0.01865323, -0.04051315, -0.01235387, ...,  0.00610587,
        -0.07179647,  0.02773852],
       ...,
       [-0.00066458,  0.04252128, -0.05645507, ...,  0.01315472,
        -0.03183565, -0.04357663],
       [-0.03317153,  0.03252457, -0.02484839, ...,  0.0117442 ,
         0.05747127,  0.00571023],
       [-0.00166393,  0.00413825, -0.04597083, ...,  0.02008525,
         0.05656247, -0.00161595]], dtype=float32)

In [17]:
dim = vectors.shape[1]

In [18]:
dim

768

In [19]:
## build a FAISS index for vectors

In [20]:
import faiss

In [21]:
index=faiss.IndexFlat(dim)

In [22]:
index

<faiss.swigfaiss.IndexFlat; proxy of <Swig Object of type 'faiss::IndexFlat *' at 0x0000028F01263DB0> >

In [23]:
index.add(vectors)

In [24]:
index

<faiss.swigfaiss.IndexFlat; proxy of <Swig Object of type 'faiss::IndexFlat *' at 0x0000028F01263DB0> >

In [35]:
search_query = "Your dressing sence is too good"

vec = encoder.encode(search_query)

In [36]:
import numpy as np

svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [37]:
## encoded the input search query

In [38]:
distances, I = index.search(svec, k=2)
distances

array([[1.4602716, 1.5301614]], dtype=float32)

In [39]:
I

array([[2, 3]], dtype=int64)

In [40]:
row_indices = I.tolist()[0]
row_indices

[2, 3]

In [41]:
df.loc[row_indices]

text category
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion